spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hjznb
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j     #druid
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
